export const operationsEn = {
  tab: "Operations",
  title: "Operations center",
  description:
    "Safe multi-account controls, notifications, and recovery backups.",
  groupsTitle: "Account groups",
  groupsDescription: "Bulk actions are deliberately limited to pause and stop.",
  groupName: "Group name",
  chooseAccounts: "Choose accounts",
  noAccountsForGroup: "Add an account before creating a group.",
  createGroup: "Create group",
  noGroups: "No account groups yet.",
  selectedAccounts: "{count} accounts",
  pauseGroup: "Pause group",
  stopGroup: "Stop group",
  deleteGroup: "Delete group",
  confirmDeleteGroup:
    'Delete account group "{name}"? The accounts themselves are not deleted.',
  actionResults: "Last bulk result",
  success: "OK",
  notificationsTitle: "Notification center",
  notificationsDescription:
    "Browser alerts stay local; webhooks receive only redacted event metadata.",
  browserRule: "Enable browser alerts",
  browserUnsupported: "Browser notifications are unavailable here.",
  permissionDenied: "Notification permission was not granted.",
  webhookName: "Webhook name",
  webhookUrl: "Webhook URL (HTTPS recommended)",
  addWebhook: "Add webhook",
  eventTypes:
    "Events: login required, reconnect errors, real-session pauses, schedule failures, and safety caps.",
  noRules: "No notification rules yet.",
  browser: "Browser",
  webhook: "Webhook",
  enabled: "Enabled",
  browserRuleDisplayName: "Browser alerts",
  notificationStates: {
    disabled: "Disabled",
    active: "Active",
    retrying: "Retrying",
    failed: "Delivery failing",
    suspended: "Suspended",
  },
  notificationFailures: "{count} consecutive failures",
  notificationNextRetry: "next retry {date}",
  notificationSuspendedUntil: "suspended until {date}",
  deleteRule: "Delete rule",
  confirmDeleteRule: 'Delete notification rule "{name}"?',
  backupTitle: "Encrypted recovery backup",
  backupDescription:
    "Downloads a consistent database snapshot and its encryption key. Restore is intentionally offline only.",
  passphrase: "Backup passphrase",
  repeatPassphrase: "Repeat passphrase",
  passphraseHint: "Use at least 12 characters and store it separately.",
  passphraseMismatch: "The passphrases do not match.",
  downloadBackup: "Download encrypted backup",
  downloading: "Creating backup...",
  restoreHint:
    "Offline restore: stop SteamBee, then run node dist/restore.js --input <file> --data-dir /data.",
  saved: "Saved.",
  loading: "Loading operation data...",
  retry: "Try again",
  failed: "The operation failed.",
  safety: "Safety",
  safetyTitle: "Session safety",
  safetyDescription:
    "Safety caps only pause an existing session. A timed pause resumes that same session when it expires; caps never start a stopped account. Daily and weekly limits reset on UTC calendar boundaries.",
  sessionLimit: "Maximum session (minutes)",
  dailyLimit: "Maximum per day (minutes)",
  weeklyLimit: "Maximum per week (minutes)",
  invalidSafetyValue:
    "Enter whole minutes within the shown ranges, or leave a safety cap empty for no limit.",
  noLimit: "No limit",
  saveSafety: "Save safety policy",
  pauseOneHour: "Pause 1 hour",
  pauseOneDay: "Pause 24 hours",
  activeHold: "Active hold: {reason}",
  holdUntil: "until {date}",
  recoveryTitle: "Recovery health",
  lastSteamContact: "Last Steam contact",
  nextRetry: "Next retry",
  retryAttempt: "Retry attempt {count}",
  sessionConflictCooldown: "60-minute cooldown",
  librarySnapshot: "Library snapshot",
  tokenExpiry: "Token expiry",
  never: "Not recorded",
  timelineTitle: "Next 7 days",
  timelineDescription:
    "Read-only preview using the scheduler's timezone rules. Winner means the active window at that row's start; a later overlap can take over.",
  refreshTimeline: "Refresh preview",
  skipNext: "Skip next",
  skipped: "Skipped",
  winner: "Winner at start",
  conflict: "Overlap",
  noUpcomingRuns: "No upcoming schedule windows.",
  goalsTitle: "Snapshot goals",
  goalsDescription:
    "Read-only progress from the last manual Steam library import. Goals never start or poll Steam.",
  chooseGame: "Choose imported game",
  targetHours: "Target hours",
  saveGoal: "Save goal",
  deleteGoal: "Delete goal",
  confirmDeleteGoal: 'Delete the snapshot goal for "{name}"?',
  snapshotAt: "Snapshot {date}",
  holdReasons: {
    manual: "Manual pause",
    pause_until: "Timed pause",
    session_limit: "Session limit",
    daily_limit: "Daily limit",
    weekly_limit: "Weekly limit",
    safety_failure: "Safety enforcement needs attention",
  },
  errorClasses: {
    none: "No error",
    transient: "Temporary error",
    rate_limited: "Rate limited",
    authentication: "Authentication error",
    session_replaced: "Session replaced",
    terminal: "Unrecoverable error",
    unknown: "Unknown error",
  },
  recoveryActions: {
    none: "No recovery action required",
    wait: "Wait and retry",
    retry: "Reconnect",
    reauthenticate: "Sign in again",
    attention: "Inspect and stop the Steam client",
  },
} as const;

type WidenOperations<T> = T extends string
  ? string
  : T extends object
    ? { [Key in keyof T]: WidenOperations<T[Key]> }
    : T;
export type OperationsCopy = WidenOperations<typeof operationsEn>;

export const operationsDe: OperationsCopy = {
  tab: "Betrieb",
  title: "Operations Center",
  description:
    "Sichere Multi-Account-Steuerung, Benachrichtigungen und Recovery-Backups.",
  groupsTitle: "Account-Gruppen",
  groupsDescription:
    "Bulk-Aktionen sind bewusst auf Pausieren und Stoppen begrenzt.",
  groupName: "Gruppenname",
  chooseAccounts: "Accounts auswählen",
  noAccountsForGroup:
    "Lege zuerst einen Account an, bevor du eine Gruppe erstellst.",
  createGroup: "Gruppe anlegen",
  noGroups: "Noch keine Account-Gruppen.",
  selectedAccounts: "{count} Accounts",
  pauseGroup: "Gruppe pausieren",
  stopGroup: "Gruppe stoppen",
  deleteGroup: "Gruppe löschen",
  confirmDeleteGroup:
    'Account-Gruppe "{name}" löschen? Die Accounts selbst werden nicht gelöscht.',
  actionResults: "Letztes Bulk-Ergebnis",
  success: "OK",
  notificationsTitle: "Notification Center",
  notificationsDescription:
    "Browser-Hinweise bleiben lokal; Webhooks erhalten nur redigierte Event-Metadaten.",
  browserRule: "Browser-Hinweise aktivieren",
  browserUnsupported: "Browser-Benachrichtigungen sind hier nicht verfügbar.",
  permissionDenied: "Die Benachrichtigungsberechtigung wurde nicht erteilt.",
  webhookName: "Webhook-Name",
  webhookUrl: "Webhook-URL (HTTPS empfohlen)",
  addWebhook: "Webhook hinzufügen",
  eventTypes:
    "Events: Login nötig, Reconnect-Fehler, echte Spielsitzung, Zeitplanfehler und Safety-Limits.",
  noRules: "Noch keine Benachrichtigungsregeln.",
  browser: "Browser",
  webhook: "Webhook",
  enabled: "Aktiv",
  browserRuleDisplayName: "Browser-Hinweise",
  notificationStates: {
    disabled: "Deaktiviert",
    active: "Aktiv",
    retrying: "Erneuter Versuch",
    failed: "Zustellung fehlerhaft",
    suspended: "Ausgesetzt",
  },
  notificationFailures: "{count} aufeinanderfolgende Fehler",
  notificationNextRetry: "nächster Versuch {date}",
  notificationSuspendedUntil: "ausgesetzt bis {date}",
  deleteRule: "Regel löschen",
  confirmDeleteRule: 'Benachrichtigungsregel "{name}" löschen?',
  backupTitle: "Verschlüsseltes Recovery-Backup",
  backupDescription:
    "Lädt einen konsistenten Datenbank-Snapshot samt Schlüssel herunter. Restore bleibt bewusst offline.",
  passphrase: "Backup-Passphrase",
  repeatPassphrase: "Passphrase wiederholen",
  passphraseHint: "Mindestens 12 Zeichen verwenden und getrennt aufbewahren.",
  passphraseMismatch: "Die Passphrasen stimmen nicht überein.",
  downloadBackup: "Verschlüsseltes Backup laden",
  downloading: "Backup wird erstellt...",
  restoreHint:
    "Offline-Restore: SteamBee stoppen, dann node dist/restore.js --input <Datei> --data-dir /data ausführen.",
  saved: "Gespeichert.",
  loading: "Betriebsdaten werden geladen...",
  retry: "Erneut versuchen",
  failed: "Die Aktion ist fehlgeschlagen.",
  safety: "Safety",
  safetyTitle: "Session-Sicherheit",
  safetyDescription:
    "Safety-Limits pausieren nur laufende Sessions. Eine zeitlich begrenzte Pause setzt dieselbe Session nach Ablauf fort; Limits starten keinen gestoppten Account. Tages- und Wochenlimits werden an UTC-Kalendergrenzen zurückgesetzt.",
  sessionLimit: "Maximale Session (Minuten)",
  dailyLimit: "Maximum pro Tag (Minuten)",
  weeklyLimit: "Maximum pro Woche (Minuten)",
  invalidSafetyValue:
    "Ganze Minuten innerhalb der angezeigten Grenzen eingeben oder ein Safety-Limit für unbegrenzt leer lassen.",
  noLimit: "Kein Limit",
  saveSafety: "Safety-Regeln speichern",
  pauseOneHour: "1 Stunde pausieren",
  pauseOneDay: "24 Stunden pausieren",
  activeHold: "Aktive Sperre: {reason}",
  holdUntil: "bis {date}",
  recoveryTitle: "Recovery-Status",
  lastSteamContact: "Letzter Steam-Kontakt",
  nextRetry: "Nächster Versuch",
  retryAttempt: "Reconnect-Versuch {count}",
  sessionConflictCooldown: "60-Minuten-Cooldown",
  librarySnapshot: "Library-Snapshot",
  tokenExpiry: "Token-Ablauf",
  never: "Nicht erfasst",
  timelineTitle: "Nächste 7 Tage",
  timelineDescription:
    "Read-only-Vorschau mit den Zeitzonenregeln des Schedulers. Gewinner bezeichnet das aktive Fenster beim Start dieser Zeile; eine spätere Überschneidung kann übernehmen.",
  refreshTimeline: "Vorschau aktualisieren",
  skipNext: "Nächsten überspringen",
  skipped: "Übersprungen",
  winner: "Gewinner beim Start",
  conflict: "Überschneidung",
  noUpcomingRuns: "Keine kommenden Zeitfenster.",
  goalsTitle: "Snapshot-Ziele",
  goalsDescription:
    "Read-only-Fortschritt aus dem letzten manuellen Steam-Library-Import. Ziele starten oder pollen Steam nie.",
  chooseGame: "Importiertes Spiel wählen",
  targetHours: "Zielstunden",
  saveGoal: "Ziel speichern",
  deleteGoal: "Ziel löschen",
  confirmDeleteGoal: 'Snapshot-Ziel für "{name}" löschen?',
  snapshotAt: "Snapshot {date}",
  holdReasons: {
    manual: "Manuelle Pause",
    pause_until: "Zeitlich begrenzte Pause",
    session_limit: "Session-Limit",
    daily_limit: "Tageslimit",
    weekly_limit: "Wochenlimit",
    safety_failure: "Sicherheitsstopp erfordert Aufmerksamkeit",
  },
  errorClasses: {
    none: "Kein Fehler",
    transient: "Vorübergehender Fehler",
    rate_limited: "Rate-Limit aktiv",
    authentication: "Authentifizierungsfehler",
    session_replaced: "Sitzung wurde ersetzt",
    terminal: "Nicht behebbarer Fehler",
    unknown: "Unbekannter Fehler",
  },
  recoveryActions: {
    none: "Keine Recovery-Aktion nötig",
    wait: "Warten und erneut versuchen",
    retry: "Neu verbinden",
    reauthenticate: "Erneut anmelden",
    attention: "Steam-Client prüfen und stoppen",
  },
};

export const operationsZhHans: OperationsCopy = {
  tab: "运维",
  title: "运维中心",
  description: "安全的多账户控制、通知和恢复备份。",
  groupsTitle: "账户组",
  groupsDescription: "批量操作仅限于暂停和停止。",
  groupName: "组名称",
  chooseAccounts: "选择账户",
  noAccountsForGroup: "请先添加账户，再创建组。",
  createGroup: "创建组",
  noGroups: "尚无账户组。",
  selectedAccounts: "{count} 个账户",
  pauseGroup: "暂停组",
  stopGroup: "停止组",
  deleteGroup: "删除组",
  confirmDeleteGroup: "要删除账户组“{name}”吗？账户本身不会被删除。",
  actionResults: "上次批量操作结果",
  success: "OK",
  notificationsTitle: "通知中心",
  notificationsDescription:
    "浏览器提醒仅保留在本地；Webhook 仅接收脱敏的事件元数据。",
  browserRule: "启用浏览器提醒",
  browserUnsupported: "此环境不支持浏览器通知。",
  permissionDenied: "未授予通知权限。",
  webhookName: "Webhook 名称",
  webhookUrl: "Webhook URL（建议使用 HTTPS）",
  addWebhook: "添加 Webhook",
  eventTypes: "事件：需要登录、重连错误、真实会话暂停、计划失败和安全上限。",
  noRules: "尚无通知规则。",
  browser: "浏览器",
  webhook: "Webhook",
  enabled: "已启用",
  browserRuleDisplayName: "浏览器提醒",
  notificationStates: {
    disabled: "已禁用",
    active: "正常",
    retrying: "正在重试",
    failed: "投递失败",
    suspended: "已暂停",
  },
  notificationFailures: "连续失败 {count} 次",
  notificationNextRetry: "下次重试 {date}",
  notificationSuspendedUntil: "暂停至 {date}",
  deleteRule: "删除规则",
  confirmDeleteRule: "要删除通知规则“{name}”吗？",
  backupTitle: "加密恢复备份",
  backupDescription: "下载一致的数据库快照及其加密密钥。恢复仅支持离线执行。",
  passphrase: "备份口令",
  repeatPassphrase: "重复输入口令",
  passphraseHint: "请使用至少 12 个字符，并将口令单独保存。",
  passphraseMismatch: "两次输入的口令不一致。",
  downloadBackup: "下载加密备份",
  downloading: "正在创建备份...",
  restoreHint:
    "离线恢复：停止 SteamBee，然后运行 node dist/restore.js --input <file> --data-dir /data。",
  saved: "已保存。",
  loading: "正在加载运维数据...",
  retry: "重试",
  failed: "操作失败。",
  safety: "安全",
  safetyTitle: "会话安全",
  safetyDescription:
    "安全上限只会暂停现有会话。限时暂停到期后会恢复同一会话；上限绝不会启动已停止的账户。每日和每周限额按 UTC 日历边界重置。",
  sessionLimit: "单次会话上限（分钟）",
  dailyLimit: "每日上限（分钟）",
  weeklyLimit: "每周上限（分钟）",
  invalidSafetyValue:
    "请输入所示范围内的整数分钟；若不设上限，请将对应安全限制留空。",
  noLimit: "无限制",
  saveSafety: "保存安全策略",
  pauseOneHour: "暂停 1 小时",
  pauseOneDay: "暂停 24 小时",
  activeHold: "当前暂停原因：{reason}",
  holdUntil: "直到 {date}",
  recoveryTitle: "恢复状态",
  lastSteamContact: "上次联系 Steam",
  nextRetry: "下次重试",
  retryAttempt: "第 {count} 次重试",
  sessionConflictCooldown: "60 分钟冷却期",
  librarySnapshot: "库快照",
  tokenExpiry: "令牌到期时间",
  never: "未记录",
  timelineTitle: "未来 7 天",
  timelineDescription:
    "使用调度器时区规则的只读预览。“开始时生效”表示该行开始时的活动窗口；之后的重叠可能接管。",
  refreshTimeline: "刷新预览",
  skipNext: "跳过下一次",
  skipped: "已跳过",
  winner: "开始时生效",
  conflict: "重叠",
  noUpcomingRuns: "没有即将开始的计划窗口。",
  goalsTitle: "快照目标",
  goalsDescription:
    "根据最近一次手动导入的 Steam 库显示只读进度。目标绝不会启动或轮询 Steam。",
  chooseGame: "选择已导入的游戏",
  targetHours: "目标小时数",
  saveGoal: "保存目标",
  deleteGoal: "删除目标",
  confirmDeleteGoal: "要删除“{name}”的快照目标吗？",
  snapshotAt: "快照时间：{date}",
  holdReasons: {
    manual: "手动暂停",
    pause_until: "限时暂停",
    session_limit: "单次会话上限",
    daily_limit: "每日上限",
    weekly_limit: "每周上限",
    safety_failure: "安全停止需要处理",
  },
  errorClasses: {
    none: "无错误",
    transient: "临时错误",
    rate_limited: "请求频率受限",
    authentication: "身份验证错误",
    session_replaced: "会话已被替换",
    terminal: "不可恢复的错误",
    unknown: "未知错误",
  },
  recoveryActions: {
    none: "无需恢复操作",
    wait: "等待后重试",
    retry: "重新连接",
    reauthenticate: "重新登录",
    attention: "检查并停止 Steam 客户端",
  },
};

export const operationsHi: OperationsCopy = {
  tab: "संचालन",
  title: "संचालन केंद्र",
  description: "सुरक्षित बहु-खाता नियंत्रण, सूचनाएँ और रिकवरी बैकअप।",
  groupsTitle: "खाता समूह",
  groupsDescription: "सामूहिक कार्रवाइयाँ केवल रोकने और बंद करने तक सीमित हैं।",
  groupName: "समूह का नाम",
  chooseAccounts: "खाते चुनें",
  noAccountsForGroup: "समूह बनाने से पहले एक खाता जोड़ें।",
  createGroup: "समूह बनाएँ",
  noGroups: "अभी कोई खाता समूह नहीं है।",
  selectedAccounts: "{count} खाते",
  pauseGroup: "समूह रोकें",
  stopGroup: "समूह बंद करें",
  deleteGroup: "समूह हटाएँ",
  confirmDeleteGroup: "खाता समूह “{name}” हटाएँ? खाते स्वयं नहीं हटाए जाएँगे।",
  actionResults: "पिछली सामूहिक कार्रवाई का परिणाम",
  success: "OK",
  notificationsTitle: "सूचना केंद्र",
  notificationsDescription:
    "ब्राउज़र अलर्ट स्थानीय रहते हैं; Webhook को केवल सुरक्षित इवेंट मेटाडेटा मिलता है।",
  browserRule: "ब्राउज़र अलर्ट चालू करें",
  browserUnsupported: "यहाँ ब्राउज़र सूचनाएँ उपलब्ध नहीं हैं।",
  permissionDenied: "सूचना की अनुमति नहीं दी गई।",
  webhookName: "Webhook का नाम",
  webhookUrl: "Webhook URL (HTTPS अनुशंसित)",
  addWebhook: "Webhook जोड़ें",
  eventTypes:
    "इवेंट: लॉगिन आवश्यक, दोबारा कनेक्ट करने में त्रुटियाँ, वास्तविक सत्र के कारण विराम, शेड्यूल विफलताएँ और सुरक्षा सीमाएँ।",
  noRules: "अभी कोई सूचना नियम नहीं है।",
  browser: "ब्राउज़र",
  webhook: "Webhook",
  enabled: "सक्रिय",
  browserRuleDisplayName: "ब्राउज़र अलर्ट",
  notificationStates: {
    disabled: "निष्क्रिय",
    active: "सक्रिय",
    retrying: "फिर प्रयास हो रहा है",
    failed: "डिलीवरी विफल",
    suspended: "निलंबित",
  },
  notificationFailures: "लगातार {count} विफलताएँ",
  notificationNextRetry: "अगला प्रयास {date}",
  notificationSuspendedUntil: "{date} तक निलंबित",
  deleteRule: "नियम हटाएँ",
  confirmDeleteRule: "सूचना नियम “{name}” हटाएँ?",
  backupTitle: "एन्क्रिप्टेड रिकवरी बैकअप",
  backupDescription:
    "डेटाबेस का सुसंगत स्नैपशॉट और उसकी एन्क्रिप्शन कुंजी डाउनलोड करता है। पुनर्स्थापना केवल ऑफलाइन उपलब्ध है।",
  passphrase: "बैकअप पासफ़्रेज़",
  repeatPassphrase: "पासफ़्रेज़ दोहराएँ",
  passphraseHint:
    "कम से कम 12 अक्षर इस्तेमाल करें और इसे अलग स्थान पर सुरक्षित रखें।",
  passphraseMismatch: "पासफ़्रेज़ मेल नहीं खाते।",
  downloadBackup: "एन्क्रिप्टेड बैकअप डाउनलोड करें",
  downloading: "बैकअप बनाया जा रहा है...",
  restoreHint:
    "ऑफलाइन पुनर्स्थापना: SteamBee बंद करें, फिर node dist/restore.js --input <file> --data-dir /data चलाएँ।",
  saved: "सहेजा गया।",
  loading: "संचालन डेटा लोड हो रहा है...",
  retry: "फिर प्रयास करें",
  failed: "कार्रवाई विफल रही।",
  safety: "सुरक्षा",
  safetyTitle: "सत्र सुरक्षा",
  safetyDescription:
    "सुरक्षा सीमाएँ केवल मौजूदा सत्र को रोकती हैं। समयबद्ध विराम समाप्त होने पर वही सत्र फिर शुरू होता है; सीमाएँ बंद खाते को कभी शुरू नहीं करतीं। दैनिक और साप्ताहिक सीमाएँ UTC कैलेंडर सीमाओं पर रीसेट होती हैं।",
  sessionLimit: "अधिकतम सत्र (मिनट)",
  dailyLimit: "प्रतिदिन अधिकतम (मिनट)",
  weeklyLimit: "प्रति सप्ताह अधिकतम (मिनट)",
  invalidSafetyValue:
    "दिखाई गई सीमाओं के भीतर पूरे मिनट दर्ज करें, या सीमा न रखने के लिए सुरक्षा सीमा खाली छोड़ें।",
  noLimit: "कोई सीमा नहीं",
  saveSafety: "सुरक्षा नीति सहेजें",
  pauseOneHour: "1 घंटे के लिए रोकें",
  pauseOneDay: "24 घंटे के लिए रोकें",
  activeHold: "सक्रिय रोक: {reason}",
  holdUntil: "{date} तक",
  recoveryTitle: "रिकवरी स्थिति",
  lastSteamContact: "Steam से अंतिम संपर्क",
  nextRetry: "अगला प्रयास",
  retryAttempt: "दोबारा कनेक्ट करने का प्रयास {count}",
  sessionConflictCooldown: "60 मिनट का कूलडाउन",
  librarySnapshot: "लाइब्रेरी स्नैपशॉट",
  tokenExpiry: "टोकन की समाप्ति",
  never: "दर्ज नहीं",
  timelineTitle: "अगले 7 दिन",
  timelineDescription:
    "शेड्यूलर के समय-क्षेत्र नियमों का केवल-पढ़ने योग्य पूर्वावलोकन। “शुरुआत में सक्रिय” उस पंक्ति के शुरू होने पर सक्रिय विंडो है; बाद का ओवरलैप उसकी जगह ले सकता है।",
  refreshTimeline: "पूर्वावलोकन रीफ़्रेश करें",
  skipNext: "अगला छोड़ें",
  skipped: "छोड़ा गया",
  winner: "शुरुआत में सक्रिय",
  conflict: "ओवरलैप",
  noUpcomingRuns: "कोई आगामी शेड्यूल विंडो नहीं है।",
  goalsTitle: "स्नैपशॉट लक्ष्य",
  goalsDescription:
    "अंतिम मैन्युअल Steam लाइब्रेरी आयात से केवल-पढ़ने योग्य प्रगति। लक्ष्य कभी Steam को शुरू या पोल नहीं करते।",
  chooseGame: "आयातित गेम चुनें",
  targetHours: "लक्ष्य घंटे",
  saveGoal: "लक्ष्य सहेजें",
  deleteGoal: "लक्ष्य हटाएँ",
  confirmDeleteGoal: "“{name}” का स्नैपशॉट लक्ष्य हटाएँ?",
  snapshotAt: "स्नैपशॉट {date}",
  holdReasons: {
    manual: "मैन्युअल विराम",
    pause_until: "समयबद्ध विराम",
    session_limit: "सत्र सीमा",
    daily_limit: "दैनिक सीमा",
    weekly_limit: "साप्ताहिक सीमा",
    safety_failure: "सुरक्षा रोक पर ध्यान आवश्यक है",
  },
  errorClasses: {
    none: "कोई त्रुटि नहीं",
    transient: "अस्थायी त्रुटि",
    rate_limited: "दर सीमित",
    authentication: "प्रमाणीकरण त्रुटि",
    session_replaced: "सत्र बदल दिया गया",
    terminal: "पुनर्प्राप्त न होने वाली त्रुटि",
    unknown: "अज्ञात त्रुटि",
  },
  recoveryActions: {
    none: "किसी रिकवरी कार्रवाई की आवश्यकता नहीं",
    wait: "प्रतीक्षा करके फिर प्रयास करें",
    retry: "फिर कनेक्ट करें",
    reauthenticate: "फिर लॉगिन करें",
    attention: "Steam क्लाइंट जाँचें और रोकें",
  },
};

export const operationsEs: OperationsCopy = {
  tab: "Operaciones",
  title: "Centro de operaciones",
  description:
    "Controles seguros para varias cuentas, notificaciones y copias de recuperación.",
  groupsTitle: "Grupos de cuentas",
  groupsDescription: "Las acciones en bloque se limitan a pausar y detener.",
  groupName: "Nombre del grupo",
  chooseAccounts: "Seleccionar cuentas",
  noAccountsForGroup: "Añade una cuenta antes de crear un grupo.",
  createGroup: "Crear grupo",
  noGroups: "Todavía no hay grupos de cuentas.",
  selectedAccounts: "{count} cuentas",
  pauseGroup: "Pausar grupo",
  stopGroup: "Detener grupo",
  deleteGroup: "Eliminar grupo",
  confirmDeleteGroup:
    "¿Eliminar el grupo de cuentas «{name}»? Las cuentas no se eliminarán.",
  actionResults: "Resultado de la última acción en bloque",
  success: "OK",
  notificationsTitle: "Centro de notificaciones",
  notificationsDescription:
    "Las alertas del navegador permanecen locales; los webhooks solo reciben metadatos de eventos depurados.",
  browserRule: "Activar alertas del navegador",
  browserUnsupported:
    "Las notificaciones del navegador no están disponibles aquí.",
  permissionDenied: "No se concedió permiso para mostrar notificaciones.",
  webhookName: "Nombre del webhook",
  webhookUrl: "URL del webhook (se recomienda HTTPS)",
  addWebhook: "Añadir webhook",
  eventTypes:
    "Eventos: inicio de sesión requerido, errores de reconexión, pausas por sesiones reales, fallos de programación y límites de seguridad.",
  noRules: "Todavía no hay reglas de notificación.",
  browser: "Navegador",
  webhook: "Webhook",
  enabled: "Activada",
  browserRuleDisplayName: "Alertas del navegador",
  notificationStates: {
    disabled: "Desactivada",
    active: "Activa",
    retrying: "Reintentando",
    failed: "Entrega fallida",
    suspended: "Suspendida",
  },
  notificationFailures: "{count} fallos consecutivos",
  notificationNextRetry: "próximo intento {date}",
  notificationSuspendedUntil: "suspendida hasta {date}",
  deleteRule: "Eliminar regla",
  confirmDeleteRule: "¿Eliminar la regla de notificación «{name}»?",
  backupTitle: "Copia de recuperación cifrada",
  backupDescription:
    "Descarga una instantánea coherente de la base de datos y su clave de cifrado. La restauración solo está disponible sin conexión.",
  passphrase: "Frase de contraseña de la copia",
  repeatPassphrase: "Repetir frase de contraseña",
  passphraseHint: "Usa al menos 12 caracteres y guárdala por separado.",
  passphraseMismatch: "Las frases de contraseña no coinciden.",
  downloadBackup: "Descargar copia cifrada",
  downloading: "Creando copia...",
  restoreHint:
    "Restauración sin conexión: detén SteamBee y ejecuta node dist/restore.js --input <file> --data-dir /data.",
  saved: "Guardado.",
  loading: "Cargando datos de operaciones...",
  retry: "Intentar de nuevo",
  failed: "La operación ha fallado.",
  safety: "Seguridad",
  safetyTitle: "Seguridad de la sesión",
  safetyDescription:
    "Los límites de seguridad solo pausan una sesión existente. Una pausa temporizada reanuda esa misma sesión al finalizar; los límites nunca inician una cuenta detenida. Los límites diarios y semanales se reinician según el calendario UTC.",
  sessionLimit: "Sesión máxima (minutos)",
  dailyLimit: "Máximo diario (minutos)",
  weeklyLimit: "Máximo semanal (minutos)",
  invalidSafetyValue:
    "Introduce minutos enteros dentro de los intervalos indicados o deja un límite vacío para no aplicarlo.",
  noLimit: "Sin límite",
  saveSafety: "Guardar política de seguridad",
  pauseOneHour: "Pausar 1 hora",
  pauseOneDay: "Pausar 24 horas",
  activeHold: "Pausa activa: {reason}",
  holdUntil: "hasta {date}",
  recoveryTitle: "Estado de recuperación",
  lastSteamContact: "Último contacto con Steam",
  nextRetry: "Próximo intento",
  retryAttempt: "Intento de reconexión {count}",
  sessionConflictCooldown: "Enfriamiento de 60 minutos",
  librarySnapshot: "Instantánea de la biblioteca",
  tokenExpiry: "Caducidad del token",
  never: "Sin registrar",
  timelineTitle: "Próximos 7 días",
  timelineDescription:
    "Vista previa de solo lectura con las reglas de zona horaria del programador. «Activa al inicio» indica la ventana activa al comienzo de esa fila; una superposición posterior puede sustituirla.",
  refreshTimeline: "Actualizar vista previa",
  skipNext: "Omitir siguiente",
  skipped: "Omitida",
  winner: "Activa al inicio",
  conflict: "Superposición",
  noUpcomingRuns: "No hay próximas ventanas programadas.",
  goalsTitle: "Objetivos de instantánea",
  goalsDescription:
    "Progreso de solo lectura de la última importación manual de la biblioteca de Steam. Los objetivos nunca inician ni consultan Steam.",
  chooseGame: "Seleccionar juego importado",
  targetHours: "Horas objetivo",
  saveGoal: "Guardar objetivo",
  deleteGoal: "Eliminar objetivo",
  confirmDeleteGoal: "¿Eliminar el objetivo de instantánea de «{name}»?",
  snapshotAt: "Instantánea del {date}",
  holdReasons: {
    manual: "Pausa manual",
    pause_until: "Pausa temporizada",
    session_limit: "Límite de sesión",
    daily_limit: "Límite diario",
    weekly_limit: "Límite semanal",
    safety_failure: "La parada de seguridad requiere atención",
  },
  errorClasses: {
    none: "Sin errores",
    transient: "Error temporal",
    rate_limited: "Frecuencia limitada",
    authentication: "Error de autenticación",
    session_replaced: "Sesión sustituida",
    terminal: "Error irrecuperable",
    unknown: "Error desconocido",
  },
  recoveryActions: {
    none: "No se requiere recuperación",
    wait: "Esperar y volver a intentarlo",
    retry: "Volver a conectar",
    reauthenticate: "Volver a iniciar sesión",
    attention: "Revisar y detener el cliente de Steam",
  },
};

export const operationsAr: OperationsCopy = {
  tab: "العمليات",
  title: "مركز العمليات",
  description: "عناصر تحكم آمنة لعدة حسابات وإشعارات ونسخ احتياطية للاسترداد.",
  groupsTitle: "مجموعات الحسابات",
  groupsDescription: "تقتصر الإجراءات الجماعية على الإيقاف المؤقت والإيقاف.",
  groupName: "اسم المجموعة",
  chooseAccounts: "اختيار الحسابات",
  noAccountsForGroup: "أضف حسابًا قبل إنشاء مجموعة.",
  createGroup: "إنشاء مجموعة",
  noGroups: "لا توجد مجموعات حسابات بعد.",
  selectedAccounts: "{count} حسابات",
  pauseGroup: "إيقاف المجموعة مؤقتًا",
  stopGroup: "إيقاف المجموعة",
  deleteGroup: "حذف المجموعة",
  confirmDeleteGroup:
    "هل تريد حذف مجموعة الحسابات «{name}»؟ لن تُحذف الحسابات نفسها.",
  actionResults: "نتيجة آخر إجراء جماعي",
  success: "OK",
  notificationsTitle: "مركز الإشعارات",
  notificationsDescription:
    "تبقى تنبيهات المتصفح محلية؛ ولا تستقبل Webhooks إلا بيانات وصفية منقحة للأحداث.",
  browserRule: "تفعيل تنبيهات المتصفح",
  browserUnsupported: "إشعارات المتصفح غير متاحة هنا.",
  permissionDenied: "لم يُمنح إذن الإشعارات.",
  webhookName: "اسم Webhook",
  webhookUrl: "عنوان Webhook ‏(يُنصح باستخدام HTTPS)",
  addWebhook: "إضافة Webhook",
  eventTypes:
    "الأحداث: الحاجة إلى تسجيل الدخول وأخطاء إعادة الاتصال والتوقف بسبب جلسة فعلية وإخفاقات الجدولة وحدود الأمان.",
  noRules: "لا توجد قواعد إشعارات بعد.",
  browser: "المتصفح",
  webhook: "Webhook",
  enabled: "مفعّلة",
  browserRuleDisplayName: "تنبيهات المتصفح",
  notificationStates: {
    disabled: "معطّلة",
    active: "نشطة",
    retrying: "تجري إعادة المحاولة",
    failed: "فشل التسليم",
    suspended: "معلّقة",
  },
  notificationFailures: "{count} حالات فشل متتالية",
  notificationNextRetry: "المحاولة التالية {date}",
  notificationSuspendedUntil: "معلّقة حتى {date}",
  deleteRule: "حذف القاعدة",
  confirmDeleteRule: "هل تريد حذف قاعدة الإشعارات «{name}»؟",
  backupTitle: "نسخة احتياطية مشفرة للاسترداد",
  backupDescription:
    "ينزّل لقطة متسقة من قاعدة البيانات ومفتاح تشفيرها. الاستعادة متاحة دون اتصال فقط.",
  passphrase: "عبارة مرور النسخة الاحتياطية",
  repeatPassphrase: "تكرار عبارة المرور",
  passphraseHint: "استخدم 12 محرفًا على الأقل واحفظها منفصلة.",
  passphraseMismatch: "عبارتا المرور غير متطابقتين.",
  downloadBackup: "تنزيل النسخة الاحتياطية المشفرة",
  downloading: "جارٍ إنشاء النسخة الاحتياطية...",
  restoreHint:
    "الاستعادة دون اتصال: أوقف SteamBee، ثم شغّل node dist/restore.js --input <file> --data-dir /data.",
  saved: "تم الحفظ.",
  loading: "جارٍ تحميل بيانات العمليات...",
  retry: "إعادة المحاولة",
  failed: "فشلت العملية.",
  safety: "الأمان",
  safetyTitle: "أمان الجلسة",
  safetyDescription:
    "توقف حدود الأمان جلسة موجودة مؤقتًا فقط. يستأنف التوقف المحدد بوقت الجلسة نفسها عند انتهائه؛ ولا تبدأ الحدود حسابًا متوقفًا. تُعاد تهيئة الحدود اليومية والأسبوعية عند حدود تقويم UTC.",
  sessionLimit: "الحد الأقصى للجلسة (بالدقائق)",
  dailyLimit: "الحد الأقصى يوميًا (بالدقائق)",
  weeklyLimit: "الحد الأقصى أسبوعيًا (بالدقائق)",
  invalidSafetyValue:
    "أدخل عددًا صحيحًا من الدقائق ضمن النطاقات المعروضة، أو اترك حد الأمان فارغًا لعدم تطبيق حد.",
  noLimit: "بلا حد",
  saveSafety: "حفظ سياسة الأمان",
  pauseOneHour: "إيقاف مؤقت لمدة ساعة",
  pauseOneDay: "إيقاف مؤقت لمدة 24 ساعة",
  activeHold: "إيقاف مؤقت نشط: {reason}",
  holdUntil: "حتى {date}",
  recoveryTitle: "حالة الاسترداد",
  lastSteamContact: "آخر اتصال مع Steam",
  nextRetry: "المحاولة التالية",
  retryAttempt: "محاولة إعادة الاتصال {count}",
  sessionConflictCooldown: "فترة تهدئة لمدة 60 دقيقة",
  librarySnapshot: "لقطة المكتبة",
  tokenExpiry: "انتهاء صلاحية الرمز",
  never: "غير مسجل",
  timelineTitle: "الأيام السبعة المقبلة",
  timelineDescription:
    "معاينة للقراءة فقط تستخدم قواعد المنطقة الزمنية للمجدول. تعني «النشطة عند البدء» النافذة النشطة عند بداية الصف؛ وقد يحل تداخل لاحق محلها.",
  refreshTimeline: "تحديث المعاينة",
  skipNext: "تخطي التالية",
  skipped: "تم التخطي",
  winner: "النشطة عند البدء",
  conflict: "تداخل",
  noUpcomingRuns: "لا توجد نوافذ مجدولة قادمة.",
  goalsTitle: "أهداف اللقطة",
  goalsDescription:
    "تقدم للقراءة فقط من آخر استيراد يدوي لمكتبة Steam. لا تبدأ الأهداف Steam ولا تستعلم منه.",
  chooseGame: "اختيار لعبة مستوردة",
  targetHours: "الساعات المستهدفة",
  saveGoal: "حفظ الهدف",
  deleteGoal: "حذف الهدف",
  confirmDeleteGoal: "هل تريد حذف هدف اللقطة للعبة «{name}»؟",
  snapshotAt: "اللقطة في {date}",
  holdReasons: {
    manual: "إيقاف مؤقت يدوي",
    pause_until: "إيقاف مؤقت محدد بوقت",
    session_limit: "حد الجلسة",
    daily_limit: "الحد اليومي",
    weekly_limit: "الحد الأسبوعي",
    safety_failure: "إيقاف الأمان يحتاج إلى تدخل",
  },
  errorClasses: {
    none: "لا يوجد خطأ",
    transient: "خطأ مؤقت",
    rate_limited: "تم تقييد المعدل",
    authentication: "خطأ في المصادقة",
    session_replaced: "تم استبدال الجلسة",
    terminal: "خطأ غير قابل للاسترداد",
    unknown: "خطأ غير معروف",
  },
  recoveryActions: {
    none: "لا يلزم إجراء استرداد",
    wait: "الانتظار ثم إعادة المحاولة",
    retry: "إعادة الاتصال",
    reauthenticate: "تسجيل الدخول مجددًا",
    attention: "افحص عميل Steam وأوقفه",
  },
};

export const operationsFr: OperationsCopy = {
  tab: "Opérations",
  title: "Centre des opérations",
  description:
    "Commandes sécurisées pour plusieurs comptes, notifications et sauvegardes de récupération.",
  groupsTitle: "Groupes de comptes",
  groupsDescription:
    "Les actions groupées sont limitées à la mise en pause et à l’arrêt.",
  groupName: "Nom du groupe",
  chooseAccounts: "Choisir des comptes",
  noAccountsForGroup: "Ajoutez un compte avant de créer un groupe.",
  createGroup: "Créer le groupe",
  noGroups: "Aucun groupe de comptes pour le moment.",
  selectedAccounts: "{count} comptes",
  pauseGroup: "Mettre le groupe en pause",
  stopGroup: "Arrêter le groupe",
  deleteGroup: "Supprimer le groupe",
  confirmDeleteGroup:
    "Supprimer le groupe de comptes « {name} » ? Les comptes eux-mêmes ne seront pas supprimés.",
  actionResults: "Résultat de la dernière action groupée",
  success: "OK",
  notificationsTitle: "Centre de notifications",
  notificationsDescription:
    "Les alertes du navigateur restent locales ; les webhooks ne reçoivent que des métadonnées d’événements expurgées.",
  browserRule: "Activer les alertes du navigateur",
  browserUnsupported:
    "Les notifications du navigateur ne sont pas disponibles ici.",
  permissionDenied:
    "L’autorisation d’afficher des notifications n’a pas été accordée.",
  webhookName: "Nom du webhook",
  webhookUrl: "URL du webhook (HTTPS recommandé)",
  addWebhook: "Ajouter un webhook",
  eventTypes:
    "Événements : connexion requise, erreurs de reconnexion, pauses dues à une session réelle, échecs de planification et limites de sécurité.",
  noRules: "Aucune règle de notification pour le moment.",
  browser: "Navigateur",
  webhook: "Webhook",
  enabled: "Activée",
  browserRuleDisplayName: "Alertes du navigateur",
  notificationStates: {
    disabled: "Désactivée",
    active: "Active",
    retrying: "Nouvelle tentative",
    failed: "Échec de livraison",
    suspended: "Suspendue",
  },
  notificationFailures: "{count} échecs consécutifs",
  notificationNextRetry: "prochaine tentative {date}",
  notificationSuspendedUntil: "suspendue jusqu’au {date}",
  deleteRule: "Supprimer la règle",
  confirmDeleteRule: "Supprimer la règle de notification « {name} » ?",
  backupTitle: "Sauvegarde de récupération chiffrée",
  backupDescription:
    "Télécharge un instantané cohérent de la base de données et sa clé de chiffrement. La restauration est uniquement disponible hors ligne.",
  passphrase: "Phrase secrète de la sauvegarde",
  repeatPassphrase: "Répéter la phrase secrète",
  passphraseHint: "Utilisez au moins 12 caractères et conservez-la séparément.",
  passphraseMismatch: "Les phrases secrètes ne correspondent pas.",
  downloadBackup: "Télécharger la sauvegarde chiffrée",
  downloading: "Création de la sauvegarde...",
  restoreHint:
    "Restauration hors ligne : arrêtez SteamBee, puis exécutez node dist/restore.js --input <file> --data-dir /data.",
  saved: "Enregistré.",
  loading: "Chargement des données d’exploitation...",
  retry: "Réessayer",
  failed: "L’opération a échoué.",
  safety: "Sécurité",
  safetyTitle: "Sécurité de la session",
  safetyDescription:
    "Les limites de sécurité mettent uniquement en pause une session existante. Une pause temporisée reprend cette session à son expiration ; les limites ne démarrent jamais un compte arrêté. Les limites quotidiennes et hebdomadaires suivent le calendrier UTC.",
  sessionLimit: "Durée maximale de session (minutes)",
  dailyLimit: "Maximum par jour (minutes)",
  weeklyLimit: "Maximum par semaine (minutes)",
  invalidSafetyValue:
    "Saisissez un nombre entier de minutes dans les plages indiquées, ou laissez une limite vide pour ne pas l’appliquer.",
  noLimit: "Aucune limite",
  saveSafety: "Enregistrer la politique de sécurité",
  pauseOneHour: "Mettre en pause 1 heure",
  pauseOneDay: "Mettre en pause 24 heures",
  activeHold: "Pause active : {reason}",
  holdUntil: "jusqu’au {date}",
  recoveryTitle: "État de récupération",
  lastSteamContact: "Dernier contact avec Steam",
  nextRetry: "Prochaine tentative",
  retryAttempt: "Tentative de reconnexion {count}",
  sessionConflictCooldown: "Pause de récupération de 60 minutes",
  librarySnapshot: "Instantané de la bibliothèque",
  tokenExpiry: "Expiration du jeton",
  never: "Non enregistré",
  timelineTitle: "7 prochains jours",
  timelineDescription:
    "Aperçu en lecture seule utilisant les règles de fuseau horaire du planificateur. « Active au début » désigne la fenêtre active au début de la ligne ; un chevauchement ultérieur peut prendre le relais.",
  refreshTimeline: "Actualiser l’aperçu",
  skipNext: "Ignorer la prochaine",
  skipped: "Ignorée",
  winner: "Active au début",
  conflict: "Chevauchement",
  noUpcomingRuns: "Aucune fenêtre planifiée à venir.",
  goalsTitle: "Objectifs d’instantané",
  goalsDescription:
    "Progression en lecture seule issue de la dernière importation manuelle de la bibliothèque Steam. Les objectifs ne démarrent ni n’interrogent Steam.",
  chooseGame: "Choisir un jeu importé",
  targetHours: "Heures cibles",
  saveGoal: "Enregistrer l’objectif",
  deleteGoal: "Supprimer l’objectif",
  confirmDeleteGoal: "Supprimer l’objectif d’instantané pour « {name} » ?",
  snapshotAt: "Instantané du {date}",
  holdReasons: {
    manual: "Pause manuelle",
    pause_until: "Pause temporisée",
    session_limit: "Limite de session",
    daily_limit: "Limite quotidienne",
    weekly_limit: "Limite hebdomadaire",
    safety_failure: "L’arrêt de sécurité nécessite une intervention",
  },
  errorClasses: {
    none: "Aucune erreur",
    transient: "Erreur temporaire",
    rate_limited: "Débit limité",
    authentication: "Erreur d’authentification",
    session_replaced: "Session remplacée",
    terminal: "Erreur irrécupérable",
    unknown: "Erreur inconnue",
  },
  recoveryActions: {
    none: "Aucune récupération requise",
    wait: "Attendre puis réessayer",
    retry: "Se reconnecter",
    reauthenticate: "Se reconnecter au compte",
    attention: "Vérifier et arrêter le client Steam",
  },
};

export const operationsBn: OperationsCopy = {
  tab: "পরিচালনা",
  title: "পরিচালনা কেন্দ্র",
  description:
    "নিরাপদ বহু-অ্যাকাউন্ট নিয়ন্ত্রণ, বিজ্ঞপ্তি এবং পুনরুদ্ধার ব্যাকআপ।",
  groupsTitle: "অ্যাকাউন্ট গ্রুপ",
  groupsDescription: "সমষ্টিগত কাজ শুধু বিরতি ও বন্ধ করার মধ্যে সীমাবদ্ধ।",
  groupName: "গ্রুপের নাম",
  chooseAccounts: "অ্যাকাউন্ট বেছে নিন",
  noAccountsForGroup: "গ্রুপ তৈরির আগে একটি অ্যাকাউন্ট যোগ করুন।",
  createGroup: "গ্রুপ তৈরি করুন",
  noGroups: "এখনও কোনো অ্যাকাউন্ট গ্রুপ নেই।",
  selectedAccounts: "{count}টি অ্যাকাউন্ট",
  pauseGroup: "গ্রুপ বিরতিতে রাখুন",
  stopGroup: "গ্রুপ বন্ধ করুন",
  deleteGroup: "গ্রুপ মুছুন",
  confirmDeleteGroup:
    "“{name}” অ্যাকাউন্ট গ্রুপটি মুছবেন? অ্যাকাউন্টগুলো মুছে ফেলা হবে না।",
  actionResults: "সর্বশেষ সমষ্টিগত কাজের ফলাফল",
  success: "OK",
  notificationsTitle: "বিজ্ঞপ্তি কেন্দ্র",
  notificationsDescription:
    "ব্রাউজার সতর্কতা স্থানীয় থাকে; Webhook শুধু সংশোধিত ইভেন্ট মেটাডেটা পায়।",
  browserRule: "ব্রাউজার সতর্কতা চালু করুন",
  browserUnsupported: "এখানে ব্রাউজার বিজ্ঞপ্তি পাওয়া যায় না।",
  permissionDenied: "বিজ্ঞপ্তির অনুমতি দেওয়া হয়নি।",
  webhookName: "Webhook-এর নাম",
  webhookUrl: "Webhook URL (HTTPS সুপারিশকৃত)",
  addWebhook: "Webhook যোগ করুন",
  eventTypes:
    "ইভেন্ট: লগইন প্রয়োজন, পুনঃসংযোগ ত্রুটি, বাস্তব সেশনের কারণে বিরতি, সময়সূচির ব্যর্থতা এবং নিরাপত্তা সীমা।",
  noRules: "এখনও কোনো বিজ্ঞপ্তি নিয়ম নেই।",
  browser: "ব্রাউজার",
  webhook: "Webhook",
  enabled: "সক্রিয়",
  browserRuleDisplayName: "ব্রাউজার সতর্কতা",
  notificationStates: {
    disabled: "নিষ্ক্রিয়",
    active: "সক্রিয়",
    retrying: "আবার চেষ্টা হচ্ছে",
    failed: "ডেলিভারি ব্যর্থ",
    suspended: "স্থগিত",
  },
  notificationFailures: "টানা {count}টি ব্যর্থতা",
  notificationNextRetry: "পরবর্তী চেষ্টা {date}",
  notificationSuspendedUntil: "{date} পর্যন্ত স্থগিত",
  deleteRule: "নিয়ম মুছুন",
  confirmDeleteRule: "“{name}” বিজ্ঞপ্তি নিয়মটি মুছবেন?",
  backupTitle: "এনক্রিপ্ট করা পুনরুদ্ধার ব্যাকআপ",
  backupDescription:
    "ডেটাবেসের একটি সামঞ্জস্যপূর্ণ স্ন্যাপশট এবং তার এনক্রিপশন কী ডাউনলোড করে। পুনরুদ্ধার শুধু অফলাইনে করা যায়।",
  passphrase: "ব্যাকআপ পাসফ্রেজ",
  repeatPassphrase: "পাসফ্রেজ আবার লিখুন",
  passphraseHint:
    "কমপক্ষে ১২টি অক্ষর ব্যবহার করুন এবং এটি আলাদাভাবে সংরক্ষণ করুন।",
  passphraseMismatch: "পাসফ্রেজ দুটি মেলেনি।",
  downloadBackup: "এনক্রিপ্ট করা ব্যাকআপ ডাউনলোড করুন",
  downloading: "ব্যাকআপ তৈরি হচ্ছে...",
  restoreHint:
    "অফলাইন পুনরুদ্ধার: SteamBee বন্ধ করুন, তারপর node dist/restore.js --input <file> --data-dir /data চালান।",
  saved: "সংরক্ষিত হয়েছে।",
  loading: "পরিচালনার ডেটা লোড হচ্ছে...",
  retry: "আবার চেষ্টা করুন",
  failed: "কাজটি ব্যর্থ হয়েছে।",
  safety: "নিরাপত্তা",
  safetyTitle: "সেশনের নিরাপত্তা",
  safetyDescription:
    "নিরাপত্তা সীমা শুধু বিদ্যমান সেশনকে বিরতিতে রাখে। সময়সীমাবদ্ধ বিরতি শেষ হলে একই সেশন আবার চালু হয়; সীমা কখনও বন্ধ অ্যাকাউন্ট চালু করে না। দৈনিক ও সাপ্তাহিক সীমা UTC ক্যালেন্ডারের সীমানায় পুনরায় শুরু হয়।",
  sessionLimit: "সর্বোচ্চ সেশন (মিনিট)",
  dailyLimit: "প্রতিদিন সর্বোচ্চ (মিনিট)",
  weeklyLimit: "প্রতি সপ্তাহে সর্বোচ্চ (মিনিট)",
  invalidSafetyValue:
    "দেখানো সীমার মধ্যে পূর্ণ মিনিট লিখুন, অথবা সীমা না রাখতে নিরাপত্তা সীমাটি ফাঁকা রাখুন।",
  noLimit: "কোনো সীমা নেই",
  saveSafety: "নিরাপত্তা নীতি সংরক্ষণ করুন",
  pauseOneHour: "১ ঘণ্টার জন্য বিরতিতে রাখুন",
  pauseOneDay: "২৪ ঘণ্টার জন্য বিরতিতে রাখুন",
  activeHold: "সক্রিয় বিরতি: {reason}",
  holdUntil: "{date} পর্যন্ত",
  recoveryTitle: "পুনরুদ্ধারের অবস্থা",
  lastSteamContact: "Steam-এর সঙ্গে সর্বশেষ যোগাযোগ",
  nextRetry: "পরবর্তী চেষ্টা",
  retryAttempt: "পুনঃসংযোগের চেষ্টা {count}",
  sessionConflictCooldown: "৬০ মিনিটের কুলডাউন",
  librarySnapshot: "লাইব্রেরি স্ন্যাপশট",
  tokenExpiry: "টোকেনের মেয়াদ",
  never: "রেকর্ড করা হয়নি",
  timelineTitle: "পরবর্তী ৭ দিন",
  timelineDescription:
    "সময়সূচিকারীর সময়-অঞ্চলের নিয়ম ব্যবহার করা শুধুমাত্র-পঠনযোগ্য প্রাক্‌দর্শন। “শুরুতে সক্রিয়” ওই সারির শুরুতে সক্রিয় উইন্ডো বোঝায়; পরের ওভারল্যাপ তার স্থান নিতে পারে।",
  refreshTimeline: "প্রাক্‌দর্শন হালনাগাদ করুন",
  skipNext: "পরবর্তীটি এড়িয়ে যান",
  skipped: "এড়িয়ে যাওয়া হয়েছে",
  winner: "শুরুতে সক্রিয়",
  conflict: "ওভারল্যাপ",
  noUpcomingRuns: "আসন্ন কোনো সময়সূচি উইন্ডো নেই।",
  goalsTitle: "স্ন্যাপশট লক্ষ্য",
  goalsDescription:
    "সর্বশেষ ম্যানুয়াল Steam লাইব্রেরি আমদানি থেকে শুধুমাত্র-পঠনযোগ্য অগ্রগতি। লক্ষ্য কখনও Steam চালু বা পোল করে না।",
  chooseGame: "আমদানি করা গেম বেছে নিন",
  targetHours: "লক্ষ্য ঘণ্টা",
  saveGoal: "লক্ষ্য সংরক্ষণ করুন",
  deleteGoal: "লক্ষ্য মুছুন",
  confirmDeleteGoal: "“{name}”-এর স্ন্যাপশট লক্ষ্যটি মুছবেন?",
  snapshotAt: "স্ন্যাপশট {date}",
  holdReasons: {
    manual: "ম্যানুয়াল বিরতি",
    pause_until: "সময়সীমাবদ্ধ বিরতি",
    session_limit: "সেশন সীমা",
    daily_limit: "দৈনিক সীমা",
    weekly_limit: "সাপ্তাহিক সীমা",
    safety_failure: "নিরাপত্তা বন্ধে মনোযোগ প্রয়োজন",
  },
  errorClasses: {
    none: "কোনো ত্রুটি নেই",
    transient: "সাময়িক ত্রুটি",
    rate_limited: "হারের সীমা প্রয়োগ হয়েছে",
    authentication: "প্রমাণীকরণ ত্রুটি",
    session_replaced: "সেশন প্রতিস্থাপিত হয়েছে",
    terminal: "পুনরুদ্ধার-অযোগ্য ত্রুটি",
    unknown: "অজানা ত্রুটি",
  },
  recoveryActions: {
    none: "পুনরুদ্ধার কাজের প্রয়োজন নেই",
    wait: "অপেক্ষা করে আবার চেষ্টা করুন",
    retry: "আবার সংযোগ করুন",
    reauthenticate: "আবার লগইন করুন",
    attention: "Steam ক্লায়েন্ট পরীক্ষা করে বন্ধ করুন",
  },
};

export const operationsPt: OperationsCopy = {
  tab: "Operações",
  title: "Central de operações",
  description:
    "Controles seguros para várias contas, notificações e backups de recuperação.",
  groupsTitle: "Grupos de contas",
  groupsDescription: "As ações em massa são limitadas a pausar e parar.",
  groupName: "Nome do grupo",
  chooseAccounts: "Selecionar contas",
  noAccountsForGroup: "Adicione uma conta antes de criar um grupo.",
  createGroup: "Criar grupo",
  noGroups: "Ainda não há grupos de contas.",
  selectedAccounts: "{count} contas",
  pauseGroup: "Pausar grupo",
  stopGroup: "Parar grupo",
  deleteGroup: "Excluir grupo",
  confirmDeleteGroup:
    "Excluir o grupo de contas “{name}”? As contas não serão excluídas.",
  actionResults: "Resultado da última ação em massa",
  success: "OK",
  notificationsTitle: "Central de notificações",
  notificationsDescription:
    "Os alertas do navegador permanecem locais; os webhooks recebem apenas metadados de eventos sem dados sensíveis.",
  browserRule: "Ativar alertas do navegador",
  browserUnsupported:
    "As notificações do navegador não estão disponíveis aqui.",
  permissionDenied: "A permissão para notificações não foi concedida.",
  webhookName: "Nome do webhook",
  webhookUrl: "URL do webhook (HTTPS recomendado)",
  addWebhook: "Adicionar webhook",
  eventTypes:
    "Eventos: login necessário, erros de reconexão, pausas por sessões reais, falhas de agendamento e limites de segurança.",
  noRules: "Ainda não há regras de notificação.",
  browser: "Navegador",
  webhook: "Webhook",
  enabled: "Ativada",
  browserRuleDisplayName: "Alertas do navegador",
  notificationStates: {
    disabled: "Desativada",
    active: "Ativa",
    retrying: "Tentando novamente",
    failed: "Falha na entrega",
    suspended: "Suspensa",
  },
  notificationFailures: "{count} falhas consecutivas",
  notificationNextRetry: "próxima tentativa {date}",
  notificationSuspendedUntil: "suspensa até {date}",
  deleteRule: "Excluir regra",
  confirmDeleteRule: "Excluir a regra de notificação “{name}”?",
  backupTitle: "Backup de recuperação criptografado",
  backupDescription:
    "Baixa um snapshot consistente do banco de dados e sua chave de criptografia. A restauração só é permitida offline.",
  passphrase: "Frase secreta do backup",
  repeatPassphrase: "Repetir frase secreta",
  passphraseHint: "Use pelo menos 12 caracteres e guarde-a separadamente.",
  passphraseMismatch: "As frases secretas não coincidem.",
  downloadBackup: "Baixar backup criptografado",
  downloading: "Criando backup...",
  restoreHint:
    "Restauração offline: pare o SteamBee e execute node dist/restore.js --input <file> --data-dir /data.",
  saved: "Salvo.",
  loading: "Carregando dados de operações...",
  retry: "Tentar novamente",
  failed: "A operação falhou.",
  safety: "Segurança",
  safetyTitle: "Segurança da sessão",
  safetyDescription:
    "Os limites de segurança apenas pausam uma sessão existente. Uma pausa temporizada retoma essa sessão quando expira; os limites nunca iniciam uma conta parada. Os limites diários e semanais seguem o calendário UTC.",
  sessionLimit: "Sessão máxima (minutos)",
  dailyLimit: "Máximo por dia (minutos)",
  weeklyLimit: "Máximo por semana (minutos)",
  invalidSafetyValue:
    "Insira minutos inteiros dentro dos intervalos mostrados ou deixe um limite vazio para não aplicá-lo.",
  noLimit: "Sem limite",
  saveSafety: "Salvar política de segurança",
  pauseOneHour: "Pausar por 1 hora",
  pauseOneDay: "Pausar por 24 horas",
  activeHold: "Pausa ativa: {reason}",
  holdUntil: "até {date}",
  recoveryTitle: "Estado de recuperação",
  lastSteamContact: "Último contato com o Steam",
  nextRetry: "Próxima tentativa",
  retryAttempt: "Tentativa de reconexão {count}",
  sessionConflictCooldown: "Intervalo de 60 minutos",
  librarySnapshot: "Snapshot da biblioteca",
  tokenExpiry: "Expiração do token",
  never: "Não registrado",
  timelineTitle: "Próximos 7 dias",
  timelineDescription:
    "Prévia somente leitura que usa as regras de fuso horário do agendador. “Ativa no início” indica a janela ativa no começo da linha; uma sobreposição posterior pode assumir o controle.",
  refreshTimeline: "Atualizar prévia",
  skipNext: "Ignorar próxima",
  skipped: "Ignorada",
  winner: "Ativa no início",
  conflict: "Sobreposição",
  noUpcomingRuns: "Não há próximas janelas agendadas.",
  goalsTitle: "Metas de snapshot",
  goalsDescription:
    "Progresso somente leitura da última importação manual da biblioteca do Steam. As metas nunca iniciam nem consultam o Steam.",
  chooseGame: "Selecionar jogo importado",
  targetHours: "Horas desejadas",
  saveGoal: "Salvar meta",
  deleteGoal: "Excluir meta",
  confirmDeleteGoal: "Excluir a meta de snapshot de “{name}”?",
  snapshotAt: "Snapshot de {date}",
  holdReasons: {
    manual: "Pausa manual",
    pause_until: "Pausa temporizada",
    session_limit: "Limite da sessão",
    daily_limit: "Limite diário",
    weekly_limit: "Limite semanal",
    safety_failure: "A parada de segurança requer atenção",
  },
  errorClasses: {
    none: "Sem erro",
    transient: "Erro temporário",
    rate_limited: "Taxa limitada",
    authentication: "Erro de autenticação",
    session_replaced: "Sessão substituída",
    terminal: "Erro irrecuperável",
    unknown: "Erro desconhecido",
  },
  recoveryActions: {
    none: "Nenhuma recuperação necessária",
    wait: "Aguardar e tentar novamente",
    retry: "Reconectar",
    reauthenticate: "Entrar novamente",
    attention: "Verificar e parar o cliente Steam",
  },
};

export const operationsId: OperationsCopy = {
  tab: "Operasi",
  title: "Pusat operasi",
  description:
    "Kontrol multiakun yang aman, notifikasi, dan cadangan pemulihan.",
  groupsTitle: "Grup akun",
  groupsDescription:
    "Tindakan massal dibatasi hanya untuk menjeda dan menghentikan.",
  groupName: "Nama grup",
  chooseAccounts: "Pilih akun",
  noAccountsForGroup: "Tambahkan akun sebelum membuat grup.",
  createGroup: "Buat grup",
  noGroups: "Belum ada grup akun.",
  selectedAccounts: "{count} akun",
  pauseGroup: "Jeda grup",
  stopGroup: "Hentikan grup",
  deleteGroup: "Hapus grup",
  confirmDeleteGroup:
    "Hapus grup akun “{name}”? Akunnya sendiri tidak akan dihapus.",
  actionResults: "Hasil tindakan massal terakhir",
  success: "OK",
  notificationsTitle: "Pusat notifikasi",
  notificationsDescription:
    "Peringatan browser tetap lokal; webhook hanya menerima metadata peristiwa yang telah disamarkan.",
  browserRule: "Aktifkan peringatan browser",
  browserUnsupported: "Notifikasi browser tidak tersedia di sini.",
  permissionDenied: "Izin notifikasi tidak diberikan.",
  webhookName: "Nama webhook",
  webhookUrl: "URL webhook (HTTPS disarankan)",
  addWebhook: "Tambahkan webhook",
  eventTypes:
    "Peristiwa: perlu masuk, kesalahan koneksi ulang, jeda karena sesi nyata, kegagalan jadwal, dan batas keamanan.",
  noRules: "Belum ada aturan notifikasi.",
  browser: "Browser",
  webhook: "Webhook",
  enabled: "Aktif",
  browserRuleDisplayName: "Peringatan browser",
  notificationStates: {
    disabled: "Nonaktif",
    active: "Aktif",
    retrying: "Mencoba lagi",
    failed: "Pengiriman gagal",
    suspended: "Ditangguhkan",
  },
  notificationFailures: "{count} kegagalan berturut-turut",
  notificationNextRetry: "percobaan berikutnya {date}",
  notificationSuspendedUntil: "ditangguhkan hingga {date}",
  deleteRule: "Hapus aturan",
  confirmDeleteRule: "Hapus aturan notifikasi “{name}”?",
  backupTitle: "Cadangan pemulihan terenkripsi",
  backupDescription:
    "Mengunduh snapshot basis data yang konsisten beserta kunci enkripsinya. Pemulihan hanya tersedia secara offline.",
  passphrase: "Frasa sandi cadangan",
  repeatPassphrase: "Ulangi frasa sandi",
  passphraseHint: "Gunakan sedikitnya 12 karakter dan simpan secara terpisah.",
  passphraseMismatch: "Frasa sandi tidak cocok.",
  downloadBackup: "Unduh cadangan terenkripsi",
  downloading: "Membuat cadangan...",
  restoreHint:
    "Pemulihan offline: hentikan SteamBee, lalu jalankan node dist/restore.js --input <file> --data-dir /data.",
  saved: "Tersimpan.",
  loading: "Memuat data operasi...",
  retry: "Coba lagi",
  failed: "Operasi gagal.",
  safety: "Keamanan",
  safetyTitle: "Keamanan sesi",
  safetyDescription:
    "Batas keamanan hanya menjeda sesi yang sudah ada. Jeda berjangka melanjutkan sesi yang sama setelah berakhir; batas tidak pernah memulai akun yang dihentikan. Batas harian dan mingguan diatur ulang pada batas kalender UTC.",
  sessionLimit: "Sesi maksimum (menit)",
  dailyLimit: "Maksimum per hari (menit)",
  weeklyLimit: "Maksimum per minggu (menit)",
  invalidSafetyValue:
    "Masukkan jumlah menit bulat dalam rentang yang ditampilkan, atau kosongkan batas keamanan jika tidak ingin membatasi.",
  noLimit: "Tanpa batas",
  saveSafety: "Simpan kebijakan keamanan",
  pauseOneHour: "Jeda 1 jam",
  pauseOneDay: "Jeda 24 jam",
  activeHold: "Jeda aktif: {reason}",
  holdUntil: "hingga {date}",
  recoveryTitle: "Status pemulihan",
  lastSteamContact: "Kontak terakhir dengan Steam",
  nextRetry: "Percobaan berikutnya",
  retryAttempt: "Percobaan koneksi ulang {count}",
  sessionConflictCooldown: "Jeda 60 menit",
  librarySnapshot: "Snapshot pustaka",
  tokenExpiry: "Kedaluwarsa token",
  never: "Belum tercatat",
  timelineTitle: "7 hari berikutnya",
  timelineDescription:
    "Pratinjau hanya baca yang menggunakan aturan zona waktu penjadwal. “Aktif saat mulai” berarti jendela yang aktif pada awal baris; tumpang tindih berikutnya dapat mengambil alih.",
  refreshTimeline: "Segarkan pratinjau",
  skipNext: "Lewati berikutnya",
  skipped: "Dilewati",
  winner: "Aktif saat mulai",
  conflict: "Tumpang tindih",
  noUpcomingRuns: "Tidak ada jendela jadwal mendatang.",
  goalsTitle: "Target snapshot",
  goalsDescription:
    "Progres hanya baca dari impor manual pustaka Steam terakhir. Target tidak pernah memulai atau melakukan polling ke Steam.",
  chooseGame: "Pilih game yang diimpor",
  targetHours: "Target jam",
  saveGoal: "Simpan target",
  deleteGoal: "Hapus target",
  confirmDeleteGoal: "Hapus target snapshot untuk “{name}”?",
  snapshotAt: "Snapshot {date}",
  holdReasons: {
    manual: "Jeda manual",
    pause_until: "Jeda berjangka",
    session_limit: "Batas sesi",
    daily_limit: "Batas harian",
    weekly_limit: "Batas mingguan",
    safety_failure: "Penghentian keamanan perlu diperiksa",
  },
  errorClasses: {
    none: "Tidak ada kesalahan",
    transient: "Kesalahan sementara",
    rate_limited: "Laju dibatasi",
    authentication: "Kesalahan autentikasi",
    session_replaced: "Sesi digantikan",
    terminal: "Kesalahan yang tidak dapat dipulihkan",
    unknown: "Kesalahan tidak diketahui",
  },
  recoveryActions: {
    none: "Tidak perlu tindakan pemulihan",
    wait: "Tunggu lalu coba lagi",
    retry: "Hubungkan kembali",
    reauthenticate: "Masuk kembali",
    attention: "Periksa dan hentikan klien Steam",
  },
};

export const operationsUr: OperationsCopy = {
  tab: "آپریشنز",
  title: "آپریشنز مرکز",
  description: "متعدد اکاؤنٹس کے محفوظ کنٹرول، اطلاعات اور بحالی کے بیک اپ۔",
  groupsTitle: "اکاؤنٹ گروپس",
  groupsDescription:
    "اجتماعی کارروائیاں صرف عارضی توقف اور بند کرنے تک محدود ہیں۔",
  groupName: "گروپ کا نام",
  chooseAccounts: "اکاؤنٹس منتخب کریں",
  noAccountsForGroup: "گروپ بنانے سے پہلے ایک اکاؤنٹ شامل کریں۔",
  createGroup: "گروپ بنائیں",
  noGroups: "ابھی کوئی اکاؤنٹ گروپ نہیں ہے۔",
  selectedAccounts: "{count} اکاؤنٹس",
  pauseGroup: "گروپ عارضی طور پر روکیں",
  stopGroup: "گروپ بند کریں",
  deleteGroup: "گروپ حذف کریں",
  confirmDeleteGroup:
    "کیا اکاؤنٹ گروپ ”{name}“ حذف کرنا ہے؟ اکاؤنٹس خود حذف نہیں ہوں گے۔",
  actionResults: "آخری اجتماعی کارروائی کا نتیجہ",
  success: "OK",
  notificationsTitle: "اطلاعاتی مرکز",
  notificationsDescription:
    "براؤزر الرٹس مقامی رہتے ہیں؛ Webhook کو صرف حساس معلومات سے پاک ایونٹ میٹا ڈیٹا ملتا ہے۔",
  browserRule: "براؤزر الرٹس فعال کریں",
  browserUnsupported: "یہاں براؤزر اطلاعات دستیاب نہیں ہیں۔",
  permissionDenied: "اطلاعات کی اجازت نہیں دی گئی۔",
  webhookName: "Webhook کا نام",
  webhookUrl: "Webhook URL ‏(HTTPS تجویز کردہ)",
  addWebhook: "Webhook شامل کریں",
  eventTypes:
    "ایونٹس: لاگ اِن درکار، دوبارہ اتصال کی خرابیاں، حقیقی سیشن کی وجہ سے توقف، شیڈول کی ناکامیاں اور حفاظتی حدود۔",
  noRules: "ابھی کوئی اطلاعاتی اصول نہیں ہے۔",
  browser: "براؤزر",
  webhook: "Webhook",
  enabled: "فعال",
  browserRuleDisplayName: "براؤزر الرٹس",
  notificationStates: {
    disabled: "غیر فعال",
    active: "فعال",
    retrying: "دوبارہ کوشش جاری",
    failed: "ترسیل ناکام",
    suspended: "معطل",
  },
  notificationFailures: "مسلسل {count} ناکامیاں",
  notificationNextRetry: "اگلی کوشش {date}",
  notificationSuspendedUntil: "{date} تک معطل",
  deleteRule: "اصول حذف کریں",
  confirmDeleteRule: "کیا اطلاعاتی اصول ”{name}“ حذف کرنا ہے؟",
  backupTitle: "رمز شدہ بحالی بیک اپ",
  backupDescription:
    "ڈیٹابیس کا مستقل اسنیپ شاٹ اور اس کی رمز نگاری کلید ڈاؤن لوڈ کرتا ہے۔ بحالی صرف آف لائن دستیاب ہے۔",
  passphrase: "بیک اپ پاس فریز",
  repeatPassphrase: "پاس فریز دوبارہ لکھیں",
  passphraseHint: "کم از کم 12 حروف استعمال کریں اور اسے الگ محفوظ رکھیں۔",
  passphraseMismatch: "پاس فریز آپس میں مماثل نہیں ہیں۔",
  downloadBackup: "رمز شدہ بیک اپ ڈاؤن لوڈ کریں",
  downloading: "بیک اپ بنایا جا رہا ہے...",
  restoreHint:
    "آف لائن بحالی: SteamBee بند کریں، پھر node dist/restore.js --input <file> --data-dir /data چلائیں۔",
  saved: "محفوظ ہو گیا۔",
  loading: "آپریشنز کا ڈیٹا لوڈ ہو رہا ہے...",
  retry: "دوبارہ کوشش کریں",
  failed: "کارروائی ناکام ہو گئی۔",
  safety: "حفاظت",
  safetyTitle: "سیشن کی حفاظت",
  safetyDescription:
    "حفاظتی حدود صرف موجودہ سیشن کو عارضی طور پر روکتی ہیں۔ مقررہ مدت کا توقف ختم ہونے پر وہی سیشن دوبارہ شروع ہوتا ہے؛ حدود کبھی بند اکاؤنٹ کو شروع نہیں کرتیں۔ روزانہ اور ہفتہ وار حدود UTC کیلنڈر کی سرحدوں پر دوبارہ مقرر ہوتی ہیں۔",
  sessionLimit: "زیادہ سے زیادہ سیشن (منٹ)",
  dailyLimit: "روزانہ زیادہ سے زیادہ (منٹ)",
  weeklyLimit: "ہفتہ وار زیادہ سے زیادہ (منٹ)",
  invalidSafetyValue:
    "دکھائی گئی حدود کے اندر پورے منٹ درج کریں، یا حد نہ رکھنے کے لیے حفاظتی حد خالی چھوڑ دیں۔",
  noLimit: "کوئی حد نہیں",
  saveSafety: "حفاظتی پالیسی محفوظ کریں",
  pauseOneHour: "1 گھنٹے کے لیے روکیں",
  pauseOneDay: "24 گھنٹے کے لیے روکیں",
  activeHold: "فعال توقف: {reason}",
  holdUntil: "{date} تک",
  recoveryTitle: "بحالی کی حالت",
  lastSteamContact: "Steam سے آخری رابطہ",
  nextRetry: "اگلی کوشش",
  retryAttempt: "دوبارہ اتصال کی کوشش {count}",
  sessionConflictCooldown: "60 منٹ کا کول ڈاؤن",
  librarySnapshot: "لائبریری اسنیپ شاٹ",
  tokenExpiry: "ٹوکن کی میعاد",
  never: "درج نہیں",
  timelineTitle: "اگلے 7 دن",
  timelineDescription:
    "شیڈیولر کے ٹائم زون اصول استعمال کرنے والا صرف مطالعہ کے لیے پیش منظر۔ ”آغاز پر فعال“ سے مراد قطار کے آغاز پر فعال ونڈو ہے؛ بعد کا اوورلیپ اس کی جگہ لے سکتا ہے۔",
  refreshTimeline: "پیش منظر تازہ کریں",
  skipNext: "اگلا چھوڑ دیں",
  skipped: "چھوڑ دیا گیا",
  winner: "آغاز پر فعال",
  conflict: "اوورلیپ",
  noUpcomingRuns: "کوئی آئندہ شیڈول ونڈو نہیں ہے۔",
  goalsTitle: "اسنیپ شاٹ اہداف",
  goalsDescription:
    "آخری دستی Steam لائبریری درآمد سے صرف مطالعہ کے لیے پیش رفت۔ اہداف کبھی Steam کو شروع یا پول نہیں کرتے۔",
  chooseGame: "درآمد شدہ گیم منتخب کریں",
  targetHours: "ہدفی گھنٹے",
  saveGoal: "ہدف محفوظ کریں",
  deleteGoal: "ہدف حذف کریں",
  confirmDeleteGoal: "کیا ”{name}“ کا اسنیپ شاٹ ہدف حذف کرنا ہے؟",
  snapshotAt: "اسنیپ شاٹ {date}",
  holdReasons: {
    manual: "دستی توقف",
    pause_until: "مقررہ مدت کا توقف",
    session_limit: "سیشن کی حد",
    daily_limit: "روزانہ کی حد",
    weekly_limit: "ہفتہ وار حد",
    safety_failure: "حفاظتی روک پر توجہ درکار ہے",
  },
  errorClasses: {
    none: "کوئی خرابی نہیں",
    transient: "عارضی خرابی",
    rate_limited: "شرح محدود ہے",
    authentication: "تصدیق کی خرابی",
    session_replaced: "سیشن تبدیل ہو گیا",
    terminal: "ناقابل بحالی خرابی",
    unknown: "نامعلوم خرابی",
  },
  recoveryActions: {
    none: "بحالی کی کارروائی درکار نہیں",
    wait: "انتظار کر کے دوبارہ کوشش کریں",
    retry: "دوبارہ منسلک کریں",
    reauthenticate: "دوبارہ لاگ اِن کریں",
    attention: "Steam کلائنٹ کو جانچ کر روکیں",
  },
};
